services:
  bbsmg:
    build:
      context: ..
      dockerfile: docker/Dockerfile.bbsmg
    image: bbsmg-phase1:latest
    container_name: bbsmg_phase1
    command: /bin/bash
    tty: true
    network_mode: host
    stdin_open: true
    stop_grace_period: 1s

    volumes:
      - ../BBSMG_ws:/BBSMG_ws

    working_dir:
      /BBSMG_ws